version: "3.8"

services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: "npm run start:dev"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000

volumes:
  db_data: {}