name: AsyncAPI Documentation

on:
  push:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v2
        
      - name: Validate AsyncAPI file
        id: validate
        uses: asyncapi/github-action-for-cli@v3.1.1 
        with:
          command: validate
          filepath: docs/asyncapi.yml

  generate:
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ needs.validate.outputs.status == 'success' }}
    steps:
      - name: Get Repo
        uses: actions/checkout@v2
      
      - name: Generate AsyncAPI documentation
        uses: asyncapi/github-action-for-cli@v3.1.1 
        with:
          template: '@asyncapi/html-template@0.9.0'  
          filepath: docs/asyncapi.yaml
          parameters: -p baseHref=/test-experiment/${{ github.ref_slug }}/ sidebarOrganization=byTags #space separated list of key/values
          output: generated-html