name: AsyncAPI Documentation
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: write
  actions: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v2
      
      - name: Generate AsyncAPI documentation
        uses: asyncapi/github-action-for-cli@v3.1.1 
        with:
          template: '@asyncapi/html-template@0.28.0'  
          filepath: docs/asyncapi.yaml
          output: generated-html-
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated-html-
  start_ci:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Set env
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Get Repo
        uses: actions/checkout@v2 
      - name: Start CI
        run: |
          gh workflow run 'Deploy to Vercel' --ref gh-pages