name: Validate AsyncAPI document

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: List files
      run: ls -l

    - name: Copy AsyncAPI document to the root
      run: cp docs/asyncapi.yml asyncapi.yml
      
    - name: Validating AsyncAPI document
      uses: asyncapi/github-action-for-cli@v3.1.1 
      with:
        command: validate
        filepath: docs/asyncapi.yml