name: Validate AsyncAPI Document

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Validating AsyncAPI document
      uses: asyncapi/github-action-for-cli@v3.1.1 
      with:
        command: validate
        filepath: /github/workspace/docs/asyncapi.yml
